### ISSUE TITLE
AppVeyor Python 3.5 package conflict

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#462]
The Python 3.5 AppVeyor tests fail because of conflicting package requirements:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.12*
  - python 3.5*
  - reproject
Use "conda info <package>" to see the dependencies for each package.
```

@mwcraig Is this something that can be fixed with new builds in [astropy-conda-channel](https://github.com/astropy/conda-channel-astropy)?

**Comment by bsipocz** [comment]
Could you please link a failing build? This is something I merged a fix in ci-helpers yesterday.

**Comment by MSeifert04** [comment]
@bsipocz That was 2 days ago: https://ci.appveyor.com/project/Astropy/ccdproc-iqpau/build/1.0.422/job/p40m7d354hpnh6ci

**Comment by MSeifert04** [comment]
@bsipocz Unfortunatly that still fails: https://ci.appveyor.com/project/Astropy/ccdproc-iqpau/build/1.0.423/job/p70ar3whtfieptsy#L105

**Comment by mwcraig** [comment]
There are two things (at least) missing:

- [x] astropy for numpy 1.12/python 3.x: This has been fixed on conda-forge.
- [ ] reproject for numpy 1.12 on any python. There is an open PR adding it https://github.com/conda-forge/reproject-feedstock/pull/1. The travis mac queue is pretty backed up so it may be a while (~24 hours) until this can be merged and reproject built.

**Comment by mwcraig** [comment]
Still waiting for the reproject PR to build....

**Comment by bsipocz** [comment]
Well, sorry for this mess, there are always more corner cases than expected. 
The current logic is to fall back on pip install whenever the conda install version requirements are not met. However not all packages are pip installable, and thus we still see failing builds. One way I have in mind is to loop over the dependencies one-by-one and retry the install that way, but I think it will a few days to merge it in to ``ci-helpers``.

**Comment by mwcraig** [comment]
No worries; I think conda-forge is really backed up right now because a lot of feedstocks were re-rendered a couple days ago. The travis mac backlog is not dropping to zero overnight anymore, so it is taking a while to catch up.

**Comment by mwcraig** [comment]
Linux and Windows builds for reproject are done, so I'm going to try restarting one of the failing jobs.

**Comment by mwcraig** [comment]
No luck....@bsipocz, does `ci-helpers` add conda-forge as a channel? I'm trying to figure out where the underlying conflict is in https://ci.appveyor.com/project/Astropy/ccdproc-iqpau/build/1.0.426/job/pe7yeqc1hf8g8na3#L84 now that conda-forge has astropy 1.3/numpy 1.12/python 3.5....

**Comment by bsipocz** [comment]
@mwcraig - no it doesn't, you need to add it in the repo's ``appveyor.yml``/``.travis.yml``
